version: '3.7'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=sqs,sns
      - HOSTNAME=localhost
      - USE_LIGHT_IMAGE=1
      - START_WEB=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LS_LOG=error
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"