aws:
  local:
    enabled: true
    endpoint: http://localhost:4566
  cognito:
    user-pool-id: us-east-1_6dUA640Xo
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_6dUA640Xo
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    initialization-mode: never
    url: jdbc:mysql://ecom-dev-cluster.cluster-c0nerfdjapib.us-east-1.rds.amazonaws.com:3306/academydb?allowPublicKeyRetrieval=true&useSSL=false
    username: academyms
    password: F9C5Lwc282gl
    platform: org.hibernate.dialect.MySQLDialect
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: 1
      maximumPoolSize: 10
  data:
    redis:
      host: localhost
management:
   endpoints:
      web:
         exposure:
            include: info,health,metrics,env,loggers
   metrics:
      export:
         simple:
            enabled: true
   endpoint:
      health:
         show-details: always

dashboard-ps-academy:
  user: dashboard
  pass: jmf85ofnei44kdj

academy-config:
  cache-ttl: 5d

logging:
   level:
      root: INFO
      

springdoc:
  api-docs:
    path: /api-docs  
  swagger-ui:
    enabled: false
  server_url: http://localhost:8080/
  api_version: V1
          
oauth-authentication:
  issuers:
    "PRICESHOES": "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_6dUA640Xo"
    "PROKENNEX": "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_xiCN0LMvk"

          
          
       